window.addEventListener('load', function () {
    const nameLinks = {
        "Aamir Khan": "https://www.newsfocus360.com/2024/01/aamir-khan-movies-year-wise-complete.html",
"Aaron Eckhart": "https://www.newsfocus360.com/2023/10/aaron-eckhart-movies-list.html",
"Aaron Paul": "https://www.newsfocus360.com/2023/10/aaron-paul-movies-list.html",
"Abhimanyu Singh": "https://www.newsfocus360.com/2025/03/abhimanyu-singh-movies-list.html",
"Abhirami": "https://www.newsfocus360.com/2025/05/abhirami-movies-list.html",
"Abishan Jeevinth": "https://www.newsfocus360.com/2025/04/abishan-jeevinth-movies-list.html",
"Adam Sandler": "https://www.newsfocus360.com/2023/10/adam-sandler-movies-list.html",
"Adhik Ravichandran": "https://www.newsfocus360.com/2023/11/adhik-ravichandran-all-movies-list.html",
"Aditi Rao Hydari": "https://www.newsfocus360.com/2024/03/aditi-rao-hydari-movies-list.html",
"Adivi Sesh": "https://www.newsfocus360.com/2023/10/adivi-sesh-movies-list.html",
"Adria Arjona": "https://www.newsfocus360.com/2025/05/adria-arjona-movies-list.html",
"Adrien Brody": "https://www.newsfocus360.com/2023/10/adrien-brody-movies-list.html",
"Aidan Gillen": "https://www.newsfocus360.com/2023/10/aidan-gillen-movie-list.html",
"Aidan Quinn": "https://www.newsfocus360.com/2023/10/aidan-quinn-movies-list.html",
"Aimee Lou Wood": "https://www.newsfocus360.com/2025/04/aimee-lou-wood-movies-list.html",
"Aishwarya Lekshmi": "https://www.newsfocus360.com/2025/05/aishwarya-lekshmi-movies-list.html",
"Aishwarya Rai Bachchan": "https://www.newsfocus360.com/2025/05/aishwarya-rai-bachchan-movies-list.html",
"Aishwarya Rajesh": "https://www.newsfocus360.com/2023/09/aishwarya-rajesh-movies-list.html",
"Ajay Bhupathi": "https://www.newsfocus360.com/2023/12/ajay-bhupathi-movies-year-wise-complete.html",
"Ajay Devgn": "https://www.newsfocus360.com/2024/01/ajay-devgn-all-movies-list-year-wise.html",
"Ajith Kumar": "https://www.newsfocus360.com/2023/10/ajith-kumar-movies-list.html",
"Akhil Akkineni": "https://www.newsfocus360.com/2023/10/akhil-akkineni-movies-list.html",
"Akshay Kumar": "https://www.newsfocus360.com/2023/10/akshay-kumar-movies-list.html",
"Akshaye Khanna": "https://www.newsfocus360.com/2025/05/akshaye-khanna-movies-list.html",
"Al Pacino": "https://www.newsfocus360.com/2023/09/al-pacino-movies-list.html",
"Alain Delon": "https://www.newsfocus360.com/2023/10/alain-delon-movies-list.html",
"Alan Alda": "https://www.newsfocus360.com/2023/10/alan-alda-movie-list.html",
"Alia Bhatt": "https://www.newsfocus360.com/2023/10/alia-bhatt-movies-list.html",
"Allari Naresh": "https://www.newsfocus360.com/2018/12/allari-naresh-movies-list.html",
"Allu Arjun": "https://www.newsfocus360.com/2018/12/Allu-Arjun-Movies-List.html",
"Amala Akkineni": "https://www.newsfocus360.com/2025/05/amala-akkineni-movies-list.html",
"Amber Heard": "https://www.newsfocus360.com/2023/04/amber-heard-movies-list.html",
"Amitabh Bachchan": "https://www.newsfocus360.com/2023/12/amitabh-bachchan-movies-year-wise.html",
"Ammy Virk": "https://www.newsfocus360.com/2024/01/ammy-virk-movies-list.html",
"Amol Parashar": "https://www.newsfocus360.com/2025/05/amol-parashar-movies-list.html",
"Amy Adams": "https://www.newsfocus360.com/2023/10/amy-adams-movies-list.html",
"Amy Jackson": "https://www.newsfocus360.com/2023/09/amy-jackson-movies-list.html",
"Ana de Armas": "https://www.newsfocus360.com/2023/09/ana-de-armas-all-movies-list.html",
"Ananya Panday": "https://www.newsfocus360.com/2024/02/ananya-panday-all-movies-list-year-wise.html",
"AnbAriv Stunt Master": "https://www.newsfocus360.com/2023/09/anbariv-stunt-master-movies-list.html",
"Angelina Jolie": "https://www.newsfocus360.com/2023/09/angelina-jolie-movies-list.html",
"Anikha Surendran": "https://www.newsfocus360.com/2024/01/anikha-surendran-movies-list.html",
"Anil Kapoor": "https://www.newsfocus360.com/2025/05/anil-kapoor-movies-list.html",
"Anil Ravipudi": "https://www.newsfocus360.com/2023/12/anil-ravipudi-movies-year-wise-complete.html",
"Anjali": "https://www.newsfocus360.com/2025/01/anjali-movies-list.html",
"Anupam Kher": "https://www.newsfocus360.com/2025/05/anupam-kher-movies-list.html",
"Anurag Basu": "https://www.newsfocus360.com/2025/05/anurag-basu-movies-list.html",
"Anurag Kashyap": "https://www.newsfocus360.com/2024/06/anurag-kashyap-all-movies-list-year-wise.html",
"Anushka Sharma": "https://www.newsfocus360.com/2024/01/anushka-sharma-all-movies-list-year-wise.html",
"Anushka Shetty": "https://www.newsfocus360.com/2024/01/anushka-shetty-all-movies-list-year-wise.html",
"Arun Matheswaran": "https://www.newsfocus360.com/2024/01/arun-matheswaran-movies-year-wise.html",
"Arun Vijay": "https://www.newsfocus360.com/2023/12/arun-vijay-movies-year-wise-complete.html",
"Ashish Gokhale": "https://www.newsfocus360.com/2025/05/ashish-gokhale-movies-list.html",
"Ashok Selvan": "https://www.newsfocus360.com/2025/05/ashok-selvan-movies-list.html",
"Ashok Teja": "https://www.newsfocus360.com/2025/04/ashok-teja-movies-list.html",
"Asif Ali": "https://www.newsfocus360.com/2025/05/asif-ali-movies-list.html",
"Atlee Kumar": "https://www.newsfocus360.com/2023/09/atlee-kumar-movies-list.html",
"Avneet Kaur": "https://www.newsfocus360.com/2025/05/avneet-kaur-movies-list.html",
"Balraj Sahni": "https://www.newsfocus360.com/2025/05/balraj-sahni-movies-list.html",
"Bella Ramsey": "https://www.newsfocus360.com/2025/05/bella-ramsey-movies-list.html",
"Bellamkonda Sai Srinivas": "https://www.newsfocus360.com/2025/05/bellamkonda-sai-srinivas-movies-list.html",
"Ben Affleck": "https://www.newsfocus360.com/2023/10/ben-affleck-movies-list_4.html",
"Betty Gilpin": "https://www.newsfocus360.com/2025/01/betty-gilpin-movies-and-tv-shows-list.html",
"Bhagyashree Borse": "https://www.newsfocus360.com/2025/05/bhagyashree-borse-movies-list.html",
"Bobby Deol": "https://www.newsfocus360.com/2025/05/bobby-deol-movies-list.html",
"Boyapati Srinu": "https://www.newsfocus360.com/2023/09/boyapati-srinu-movies-list.html",
"Brad Pitt": "https://www.newsfocus360.com/2023/10/brad-pitt-movies-list.html",
"Brandon Sklenar": "https://www.newsfocus360.com/2025/04/brandon-sklena-movies-list.html",
"Bruce Dern": "https://www.newsfocus360.com/2024/04/bruce-dern-movies-list.html",
"Bruce Willis": "https://www.newsfocus360.com/2023/10/bruce-willis-movies-list.html",
"Cameron Diaz": "https://www.newsfocus360.com/2023/09/cameron-diaz-movies-list.html",
"Camilla Belle": "https://www.newsfocus360.com/2025/01/camilla-belle-movies-list.html",
"Cantinflas": "https://www.newsfocus360.com/2024/01/cantinflas-all-movies-list-year-wise.html",
"Carrie Coon": "https://www.newsfocus360.com/2025/04/carrie-coon-movies-list.html",
"Chiranjeevi": "https://www.newsfocus360.com/2018/12/Chiranjeevi-movies-list.html",
"Chris Evans": "https://www.newsfocus360.com/2024/01/chris-evans-movies-list.html",
"Christopher Nolan": "https://www.newsfocus360.com/2023/10/christopher-nolan-movies-list.html",
"Daniel Day-Lewis": "https://www.newsfocus360.com/2023/10/daniel-day-lewis-movies-list.html",
"Darshan": "https://www.newsfocus360.com/2023/12/darshan-movies-year-wise-complete-list.html",
"Deepika Padukone": "https://www.newsfocus360.com/2024/01/deepika-padukone-all-movies-list-year.html",
"Deepshikha Nagpal": "https://www.newsfocus360.com/2025/05/deepshikha-nagpal-movies-list.html",
"Demi Moore": "https://www.newsfocus360.com/2023/09/demi-moore-movies-list.html",
"Denise Gough": "https://www.newsfocus360.com/2025/05/denise-gough-movies-list.html",
"Denzel Washington": "https://www.newsfocus360.com/2023/10/denzel-washington-movies-list.html",
"Desingh Periyasamy": "https://www.newsfocus360.com/2025/01/desingh-periyasamy-movies-list.html",
"Dev Anand": "https://www.newsfocus360.com/2025/05/dev-anand-movies-list.html",
"Dev Patel": "https://www.newsfocus360.com/2024/02/dev-patel-all-movies-list-year-wise.html",
"Dhanush": "https://www.newsfocus360.com/2023/10/dhanush-movies-list.html",
"Dharmendra": "https://www.newsfocus360.com/2025/05/dharmendra-movies-list.html",
"Diane Keaton": "https://www.newsfocus360.com/2024/01/diane-keaton-all-movies-list-year-wise.html",
"Disha Patani": "https://www.newsfocus360.com/2025/05/disha-patani-movies-list.html",
"Dulquer Salmaan": "https://www.newsfocus360.com/2023/10/dulquer-salmaan-movies-list.html",
"Dustin Hoffman": "https://www.newsfocus360.com/2024/01/dustin-hoffman-all-movies-list-year-wise.html",
"Dwayne Johnson": "https://www.newsfocus360.com/2023/09/the-rock-movies-list.html",
"Eesha Rebba": "https://www.newsfocus360.com/2023/11/eesha-rebba-all-movies-list.html",
"Ellen Burstyn": "https://www.newsfocus360.com/2024/01/ellen-burstyn-all-movies-list-year-wise.html",
"Emma Corrin": "https://www.newsfocus360.com/2025/05/emma-corrin-movies-list.html",
"Emma Myers": "https://www.newsfocus360.com/2025/04/emma-myers-movies-list.html",
"Emma Stone": "https://www.newsfocus360.com/2024/01/emma-stone-movies-list.html",
"Emma Thompson": "https://www.newsfocus360.com/2024/01/emma-thompson-all-movies-list-year-wise.html",
"Emraan Hashmi": "https://www.newsfocus360.com/2023/10/emraan-hashmi-movies-list.html",
"Fahadh Faasil": "https://www.newsfocus360.com/2024/11/fahadh-faasil-movies-list_28.html",
"Faria Abdullah": "https://www.newsfocus360.com/2024/05/faria-abdullah-movies-lis.html",
"Farooq Sheikh": "https://www.newsfocus360.com/2025/05/farooq-sheikh-movies-list.html",
"Finn Wolfhard": "https://www.newsfocus360.com/2023/04/blog-post.html",
"Gaurav More": "https://www.newsfocus360.com/2024/06/gaurav-more-all-movies-list-year-wise.html",
"Gavie Chahal": "https://www.newsfocus360.com/2025/05/gavie-chahal-movies-list.html",
"Gemini Ganesan": "https://www.newsfocus360.com/2025/05/gemini-ganesan-movies-list.html",
"Genelia D'Souza": "https://www.newsfocus360.com/2025/05/genelia-dsouza-movies-list.html",
"Gippy Grewal": "https://www.newsfocus360.com/2023/10/gippy-grewal-movies-list.html",
"Gopichand": "https://www.newsfocus360.com/2018/12/gopichand-movies-list.html",
"Govinda": "https://www.newsfocus360.com/2024/01/govinda-all-movies-list-year-wise.html",
"Gowtam Naidu Tinnanuri": "https://www.newsfocus360.com/2024/08/gowtam-naidu-tinnanuri-movies-list.html",
"Gowtam Tinnanuri": "https://www.newsfocus360.com/2025/05/gowtam-tinnanuri-movies-list.html",
"Guru Dutt": "https://www.newsfocus360.com/2025/05/guru-dutt-movies-list.html",
"Guy Ritchie": "https://www.newsfocus360.com/2024/02/guy-ritchie-all-movies-list-year-wise.html",
"H. Vinoth": "https://www.newsfocus360.com/2024/09/h-vinoth-movies-list-year-wise.html",
"Hailee Steinfeld": "https://www.newsfocus360.com/2025/05/hailee-steinfeld-movies-list.html",
"Harish Shankar": "https://www.newsfocus360.com/2025/05/harish-shankar-movies-list.html",
"Hebah Patel": "https://www.newsfocus360.com/2025/04/hebah-patel-movies-list.html",
"Hema Malini": "https://www.newsfocus360.com/2025/05/hema-malini-movies-list.html",
"Hina Khan": "https://www.newsfocus360.com/2024/06/hina-khan-all-movies-list-year-wise.html",
"Hrithik Roshan": "https://www.newsfocus360.com/2024/01/hrithik-roshan-all-movies-list-year-wise.html",
"Hugh Jackman": "https://www.newsfocus360.com/2024/08/hugh-jackman-movies-list-year-wise.html",
"Ida Lupino": "https://www.newsfocus360.com/2024/08/ida-lupino-movies-list-year-wise.html",
"Imogen Faith Reid": "https://www.newsfocus360.com/2025/04/imogen-faith-reid-movies-list.html",
"Indhuja Ravichandran": "https://www.newsfocus360.com/2023/11/indhuja-ravichandran-movies-year-wise.html",
"Irrfan Khan": "https://www.newsfocus360.com/2023/09/irrfan-khan-movies-list.html",
"Isabela Merced": "https://www.newsfocus360.com/2025/05/isabela-merced-movies-list.html",
"Ishaan Khatter": "https://www.newsfocus360.com/2025/05/ishaan-khatter-movies-list.html",
"Jack Black": "https://www.newsfocus360.com/2024/01/jack-black-all-movies-list-year-wise.html",
"Jack O'Connell": "https://www.newsfocus360.com/2025/05/jack-oconnell-movies-list.html",
"Jack Schumacher": "https://www.newsfocus360.com/2025/05/jack-schumacher-movies-list.html",
"Jackie Chan": "https://www.newsfocus360.com/2023/05/jackie-chan-movies-list.html",
"Jagapathi Babu": "https://www.newsfocus360.com/2024/04/jagapathi-babu-movies-list.html",
"Jamie Chung": "https://www.newsfocus360.com/2024/01/jamie-chung-all-movies-list-year-wise.html",
"Janhvi Kapoor": "https://www.newsfocus360.com/2025/05/janhvi-kapoor-movies-list.html",
"Janki Bodiwala": "https://www.newsfocus360.com/2024/06/janki-bodiwala-all-movies-list-year-wise.html",
"Jared Leto": "https://www.newsfocus360.com/2024/04/jared-leto-movies-list.html",
"Jason Isaacs": "https://www.newsfocus360.com/2025/04/jason-isaacs-movies-list.html",
"Jason Statham": "https://www.newsfocus360.com/2024/01/jason-statham-movies-list.html",
"Jaya Bachchan": "https://www.newsfocus360.com/2025/05/jaya-bachchan-movies-list.html",
"Jayam Ravi": "https://www.newsfocus360.com/2023/10/jayam-ravi-movies-list.html",
"Jeetendra": "https://www.newsfocus360.com/2025/05/jeetendra-movies-list.html",
"Jeethu Joseph": "https://www.newsfocus360.com/2024/01/jeethu-joseph-all-movies-list-year-wise.html",
"Jena Malone": "https://www.newsfocus360.com/2024/01/jena-malone-all-movies-list-year-wise.html",
"Jennifer Grey": "https://www.newsfocus360.com/2023/09/jennifer-grey-movies-list.html",
"Jennifer Lawrence": "https://www.newsfocus360.com/2023/09/jennifer-lawrence-movies-list.html",
"Jennifer Lopez": "https://www.newsfocus360.com/2024/01/jennifer-lopez-all-movies-list-year-wise.html",
"jet lee": "https://www.newsfocus360.com/2025/01/jet-li-movies-list.html",
"Joe Keery": "https://www.newsfocus360.com/2023/04/joe-keery-movies-and-tv-shows-list.html",
"John Abraham": "https://www.newsfocus360.com/2023/10/john-abraham-movies-list.html",
"Johnny Depp": "https://www.newsfocus360.com/2023/04/johnny-depp-movies-list.html",
"Joju George": "https://www.newsfocus360.com/2025/05/joju-george-movies-list.html",
"Joseph Zada": "https://www.newsfocus360.com/2025/05/joseph-zada-movies-list.html",
"Josh Duhamel": "https://www.newsfocus360.com/2025/05/josh-duhamel-movies-list.html",
"Julia Roberts": "https://www.newsfocus360.com/2024/01/julia-roberts-all-movies-list-year-wise.html",
"Kaitlyn Dever": "https://www.newsfocus360.com/2025/05/kaitlyn-dever-movies-list.html",
"Kajal Aggarwal": "https://www.newsfocus360.com/2024/01/kajal-aggarwal-all-movies-list-year-wise.html",
"Kajol": "https://www.newsfocus360.com/2025/05/kajol-movies-list.html",
"Kalees": "https://www.newsfocus360.com/2024/12/kalees-movies-list.html",
"Kamal Haasan": "https://www.newsfocus360.com/2023/10/kamal-haasan-movies-list.html",
"Kangana Ranaut": "https://www.newsfocus360.com/2024/01/kangana-ranaut-movies-year-wise.html",
"Karan Sharma": "https://www.newsfocus360.com/2025/05/karan-sharma-movies-list.html",
"Kareena Kapoor Khan": "https://www.newsfocus360.com/2024/01/kareena-kapoor-khan-all-movies-list.html",
"Karishma Kapoor": "https://www.newsfocus360.com/2024/01/karishma-kapoor-all-movies-list-year.html",
"Karisma Kapoor": "https://www.newsfocus360.com/2024/07/karisma-kapoor-all-movies-list-year-wise.html",
"karthi": "https://www.newsfocus360.com/2025/01/karthi-movies-list.html",
"Karthik Gattamneni": "https://www.newsfocus360.com/2023/11/karthik-gattamneni-all-movies-list.html",
"Karthik Subbaraj": "https://www.newsfocus360.com/2024/03/karthik-subbaraj-movies-list.html",
"Kartik Aaryan": "https://www.newsfocus360.com/2024/06/kartik-aaryan-all-movies-list-year-wise.html",
"Kate Winslet": "https://www.newsfocus360.com/2024/08/kate-winslet-movies-list-year-wise.html",
"Katrina Kaif": "https://www.newsfocus360.com/2024/01/katrina-kaif-all-movies-list-year-wise.html",
"Katt Williams": "https://www.newsfocus360.com/2024/01/katt-williams-all-movies-list-year-wise.html",
"Kavya Maran": "https://www.newsfocus360.com/2024/03/kavya-maran-movies-list.html",
"Keanu Reeves": "https://www.newsfocus360.com/2023/10/keanu-reeves-movies-list.html",
"Keerthy Suresh": "https://www.newsfocus360.com/2023/10/keerthy-suresh-movies-list.html",
"Kenneth Branagh": "https://www.newsfocus360.com/2024/01/kenneth-branagh-all-movies-list-year.html",
"Ketika Sharma": "https://www.newsfocus360.com/2023/11/ketika-sharma-all-movies-list.html",
"Kevin James": "https://www.newsfocus360.com/2024/01/kevin-james-all-movies-list-year-wise.html",
"Kiara Advani": "https://www.newsfocus360.com/2024/01/kiara-advani-movies-list.html",
"Kiran Abbavaram": "https://www.newsfocus360.com/2023/12/kiran-abbavaram-movies-year-wise.html",
"Kirsten Dunst": "https://www.newsfocus360.com/2024/02/kirsten-dunst-all-movies-list-year-wise.html",
"Konkona Sen Sharma": "https://www.newsfocus360.com/2025/05/konkona-sen-sharma-movies-list.html",
"Krish Jagarlamudi": "https://www.newsfocus360.com/2023/09/krish-jagarlamudi-movies-list.html",
"Krithi Shetty": "https://www.newsfocus360.com/2023/10/krithi-shetty-movies-list.html",
"Lauren Compton": "https://www.newsfocus360.com/2024/01/lauren-compton-all-movies-list-year-wise.html",
"Lavanya Tripathi": "https://www.newsfocus360.com/2023/11/lavanya-tripathi-all-movies-kist.html",
"Léa Seydoux": "https://www.newsfocus360.com/2024/01/lea-seydoux-all-movies-list-year-wise.html",
"Leonardo DiCaprio": "https://www.newsfocus360.com/2023/10/leonardo-dicaprio-movies-list.html",
"Lesley Ann Warren": "https://www.newsfocus360.com/2025/02/lesley-ann-warren-movies-and-tv-shows.html",
"Leslie Bibb": "https://www.newsfocus360.com/2025/04/leslie-bibb-movies-list.html",
"Lisa": "https://www.newsfocus360.com/2025/04/lisa-movies-list.html",
"Lokesh Kanagaraj": "https://www.newsfocus360.com/2023/09/lokesh-kanagaraj-movies-list.html",
"Lokkesh Ajls": "https://www.newsfocus360.com/2025/05/lokkesh-ajls-movies-list.html",
"M. Sasikumar": "https://www.newsfocus360.com/2025/04/m-sasikumar-movies-list.html",
"Macaulay Culkin": "https://www.newsfocus360.com/2023/10/macaulay-culkin-movies-list.html",
"Madeline Brewer": "https://www.newsfocus360.com/2025/05/madeline-brewer-movies-list.html",
"Madhubala": "https://www.newsfocus360.com/2025/05/madhubala-movies-list.html",
"Madhuri Dixit": "https://www.newsfocus360.com/2024/01/madhuri-dixit-all-movies-list-year-wise.html",
"Madonna Sebastian": "https://www.newsfocus360.com/2024/01/madonna-sebastian.html",
"Mahesh Babu": "https://www.newsfocus360.com/2018/12/List-Mahesh-Babu-Movies.html",
"Mahima Nambiar": "https://www.newsfocus360.com/2023/09/mahima-nambiar-movies-list.html",
"Maika Monroe": "https://www.newsfocus360.com/2025/01/maika-monroe-movies-list.html",
"Mammootty": "https://www.newsfocus360.com/2023/09/mammootty-movies-list.html",
"Manchu Manoj": "https://www.newsfocus360.com/2025/05/manchu-manoj-movies-list.html",
"Maneesh Sharma": "https://www.newsfocus360.com/2023/09/maneesh-sharma-movies-list.html",
"Mani Ratnam": "https://www.newsfocus360.com/2023/11/mani-ratnam-all-movies-list.html",
"Manju Warrier": "https://www.newsfocus360.com/2025/05/manju-warrier-movies-list.html",
"Mannara Chopra": "https://www.newsfocus360.com/2023/10/mannara-chopra-movies-list.html",
"Manoj Bajpayee": "https://www.newsfocus360.com/2025/05/manoj-bajpayee.html",
"Manu Swaraj": "https://www.newsfocus360.com/2025/05/manu-swaraj-movies-list.html",
"Maruthi": "https://www.newsfocus360.com/2023/12/maruthi-movies-year-wise-complete-list.html",
"Matthew McConaughey": "https://www.newsfocus360.com/2025/01/matthew-mcconaughey-movies-and-tv-shows.html",
"Meena": "https://www.newsfocus360.com/2024/01/meena-all-movies-list-year-wise.html",
"Meena Kumari": "https://www.newsfocus360.com/2025/05/meena-kumari-movies-list.html",
"Meg Ryan": "https://www.newsfocus360.com/2023/10/meg-ryan-movie-list.html",
"Megan Fox": "https://www.newsfocus360.com/2023/10/megan-fox-movies-list.html",
"Meher Ramesh": "https://www.newsfocus360.com/2023/11/meher-ramesh-all-movies-list.html",
"Meryl Streep": "https://www.newsfocus360.com/2024/07/meryl-streep-movies-list-year-wise.html",
"Michael Gambon": "https://www.newsfocus360.com/2023/09/michael-gambon-movies-list.html",
"Michael Madsen": "https://www.newsfocus360.com/2025/01/michael-madsen-movies-list.html",
"Michelle Monaghan": "https://www.newsfocus360.com/2025/04/michelle-monaghan-movies-list.html",
"Mickey Rourke": "https://www.newsfocus360.com/2025/04/mickey-rourke-movies-list.html",
"Mike White": "https://www.newsfocus360.com/2025/04/mike-white-movies-list.html",
"Millie Bobby Brown": "https://www.newsfocus360.com/2025/03/millie-bobby-brown-movies-list.html",
"Minka Kelly": "https://www.newsfocus360.com/2025/05/minka-kelly-movies-list.html",
"Mithun Chakraborty": "https://www.newsfocus360.com/2025/05/mithun-chakraborty-movies-list.html",
"Mohanlal": "https://www.newsfocus360.com/2024/01/mohanlal-movies-year-wise-complete-list.html",
"Mouni Roy": "https://www.newsfocus360.com/2025/04/mouni-roy-movies-list.html",
"Mrunal Thakur": "https://www.newsfocus360.com/2023/11/mrunal-thakur-all-movies-list.html",
"Murali Sharma": "https://www.newsfocus360.com/2025/04/murali-sharma-movies-list.html",
"N. T. Rama Rao IV": "https://www.newsfocus360.com/2025/05/n-t-rama-rao-iv-movies-list.html",
"N. T. Rama Rao Jr.": "https://www.newsfocus360.com/2018/12/jr-ntr-movies-list.html",
"N. T. Rama Rao Sr.": "https://www.newsfocus360.com/2025/05/n-t-rama-rao-movies-list.html",
"Naga Chaitanya": "https://www.newsfocus360.com/2018/12/naga-chaitanya-movies-list.html",
"Naga Shaurya": "https://www.newsfocus360.com/2018/12/naga-shaurya-movies.html",
"Nagarjuna": "https://www.newsfocus360.com/2018/12/akkineni-nagarjuna-movies-list-all-hit.html",
"Nana Patekar": "https://www.newsfocus360.com/2025/05/nana-patekar-movies-list.html",
"Nandamuri Balakrishna": "https://www.newsfocus360.com/2023/10/nandamuri-balakrishna-movies-list.html",
"Nandamuri Harikrishna": "https://www.newsfocus360.com/2018/12/nandamuri-harikrishna-movies-list.html",
"Nandamuri Kalyan Ram": "https://www.newsfocus360.com/2023/12/nandamuri-kalyan-ram-movies-year-wise.html",
"Nandini Gupta": "https://www.newsfocus360.com/2025/05/nandini-gupta-movies-list.html",
"Nandita Das": "https://www.newsfocus360.com/2025/05/nandita-das-movies-list.html",
"Nani": "https://www.newsfocus360.com/2018/12/nani-all-movies-list-and-biography-hits.html",
"Nara Rohith": "https://www.newsfocus360.com/2025/05/nara-rohith-movies-list.html",
"Nargis": "https://www.newsfocus360.com/2025/05/nargis-movies-list.html",
"Naseeruddin Shah": "https://www.newsfocus360.com/2025/05/naseeruddin-shah-movies-list.html",
"Naveen Chandra": "https://www.newsfocus360.com/2025/05/naveen-chandra-movies-list.html",
"Nawazuddin Siddiqui": "https://www.newsfocus360.com/2023/10/nawazuddin-siddiqui-movies-list.html",
"Nayanthara": "https://www.newsfocus360.com/2024/01/nayanthara-all-movies-list-year-wise.html",
"Neeraj Ghaywan": "https://www.newsfocus360.com/2025/05/neeraj-ghaywan-movies-list.html",
"Neha Pathan": "https://www.newsfocus360.com/2023/11/neha-pathan-movies-year-wise-complete.html",
"Neha Shetty": "https://www.newsfocus360.com/2023/10/neha-shetty-movies-list.html",
"Nelson Dilipkumar": "https://www.newsfocus360.com/2023/11/nelson-dilipkumar-movies.html",
"Nikhil Siddhartha": "https://www.newsfocus360.com/2023/06/nikhil-siddhartha-movies-list.html",
"Nimrat Khaira": "https://www.newsfocus360.com/2025/05/nimrat-khaira-movies-list.html",
"Niranjana Anoop": "https://www.newsfocus360.com/2025/05/niranjana-anoop-movies-list.html",
"Nithin": "https://www.newsfocus360.com/2018/12/nithin-all-movies-list.html",
"Nithya Menen": "https://www.newsfocus360.com/2023/09/nithya-menen-movies-list.html",
"Nivetha Thomas": "https://www.newsfocus360.com/2023/12/nivetha-thomas-movies.html",
"Nivin Pauly": "https://www.newsfocus360.com/2023/09/nivin-pauly-movies-list.html",
"Nutan": "https://www.newsfocus360.com/2025/05/nutan-movies-list.html",
"Om Puri": "https://www.newsfocus360.com/2025/05/om-puri-movies-list.html",
"Om Raut": "https://www.newsfocus360.com/2024/01/om-raut.html",
"Owen Cooper": "https://www.newsfocus360.com/2025/03/owen-cooper-movies-list.html",
"P. Vasu": "https://www.newsfocus360.com/2023/09/p-vasu-movies-list.html",
"Pa. Ranjith": "https://www.newsfocus360.com/2024/12/pa-ranjith-movies-list.html",
"Palak Tiwari": "https://www.newsfocus360.com/2025/05/palak-tiwari-movies-list.html",
"Parasuram": "https://www.newsfocus360.com/2023/05/parasuram-movies-list-news-focus-360.html",
"Paresh Rawal": "https://www.newsfocus360.com/2025/05/paresh-rawal-movies-list.html",
"Parineeti Chopra": "https://www.newsfocus360.com/2023/09/parineeti-chopra-movies-list.html",
"Parker Posey": "https://www.newsfocus360.com/2025/04/parker-posey-movies-list.html",
"Parveen Babi": "https://www.newsfocus360.com/2025/05/parveen-babi-movies-list.html",
"Patrick Schwarzenegger": "https://www.newsfocus360.com/2025/04/patrick-schwarzenegger-movies-list.html",
"Paul Rudd": "https://www.newsfocus360.com/2024/01/paul-rudd-all-movies-list-year-wise.html",
"Pawan Kalyan": "https://www.newsfocus360.com/2023/07/pawan-kalyan-movies-list.html",
"Payal Rajput": "https://www.newsfocus360.com/2023/11/payal-rajput-all-movies-list.html",
"Pedro Pascal": "https://www.newsfocus360.com/2025/05/pedro-pascal-movies-list.html",
"penelope cruz": "https://www.newsfocus360.com/2025/01/penelope-cruz-movies-list.html",
"Penélope Cruz": "https://www.newsfocus360.com/2023/10/penelope-cruz-movies-list.html",
"Pooja Hegde": "https://www.newsfocus360.com/2025/04/pooja-hegde-movies-list.html",
"Poonam Pandey": "https://www.newsfocus360.com/2025/05/poonam-pandey-movies-list.html",
"Poornima Ravi": "https://www.newsfocus360.com/2023/10/poornima-ravi-movies-list.html",
"Prabhas": "https://www.newsfocus360.com/2018/12/prabhas-movies-list.html",
"Pradeep Ranganathan": "https://www.newsfocus360.com/2025/04/pradeep-chilukuri-movies-list.html",
"Prasanth Varma": "https://www.newsfocus360.com/2025/05/pradeep-ranganathan-movies-list.html",
"Prashanth Neel": "https://www.newsfocus360.com/2024/01/prasanth-varma.html",
"Praveen Sattaru": "https://www.newsfocus360.com/2023/09/prashanth-neel-movies-list.html",
"Preity Zinta": "https://www.newsfocus360.com/2023/09/praveen-sattaru-movies-list.html",
"Prithviraj Kapoor": "https://www.newsfocus360.com/2025/05/prithviraj-kapoor-movies-list.html",
"Prithviraj Sukumaran": "https://www.newsfocus360.com/2023/12/prithviraj-sukumaran-movies-year-wise.html",
"Priyadarshan": "https://www.newsfocus360.com/2024/06/priyadarshan.html",
"Priyadarshi Pulikonda": "https://www.newsfocus360.com/2025/03/priyadarshi-pulikonda-movies-list.html",
"Priyamani": "https://www.newsfocus360.com/2024/04/priyamani-movies-list.html",
"Priyanka Chopra": "https://www.newsfocus360.com/2025/05/priyanka-chopra-movies-list.html",
"Puneeth Rajkumar": "https://www.newsfocus360.com/2025/05/puneeth-rajkumar-movies-list.html",
"Ra Karthik": "https://www.newsfocus360.com/2025/05/ra-karthik-movies-list.html",
"Rachel Zegler": "https://www.newsfocus360.com/2025/04/rachel-zegler-movies-list.html",
"Radha": "https://www.newsfocus360.com/2024/03/radha-movies-list.html",
"Radhika": "https://www.newsfocus360.com/2024/01/radhika-all-movies-list-year-wise.html",
"Radhika Apte": "https://www.newsfocus360.com/2025/05/radhika-apte-movies-list.html",
"Raghava Lawrence": "https://www.newsfocus360.com/2023/09/raghava-lawrence-movies-list.html",
"Raj & DK": "https://www.newsfocus360.com/2025/05/raj-dk-movies-list.html",
"Raj Kapoor": "https://www.newsfocus360.com/2025/05/raj-kapoor-movies-list.html",
"Raj Kumar Gupta": "https://www.newsfocus360.com/2025/04/raj-kumar-gupta-movies-list.html",
"Rajesh Khanna": "https://www.newsfocus360.com/2025/05/rajesh-khanna-movies-list.html",
"Rajinikanth": "https://www.newsfocus360.com/2025/01/rajinikanth-movies-list.html",
"Rajisha Vijayan": "https://www.newsfocus360.com/2024/01/rajisha-vijayan-movies-year-wise.html",
"Rajkumar Hirani": "https://www.newsfocus360.com/2023/09/rajkumar-hirani-movies-list.html",
"Rajkummar Rao": "https://www.newsfocus360.com/2024/01/rajkummar-rao-all-movies-list-year-wise.html",
"Raju Murugan": "https://www.newsfocus360.com/2023/11/raju-murugan-movies.html",
"Rakesh Poojary": "https://www.newsfocus360.com/2025/05/rakesh-poojary-movies-list.html",
"Ram Charan": "https://www.newsfocus360.com/2024/01/ram-charan-all-movies-list-year-wise.html",
"Ram Gopal Varma": "https://www.newsfocus360.com/2025/04/ram-gopal-varma-movies-list.html",
"Ram Pothineni": "https://www.newsfocus360.com/2018/12/ram-pothineni-movies-list.html",
"Ranbir Kapoor": "https://www.newsfocus360.com/2024/12/ranbir-kapoor-movies-list.html",
"Randeep Hooda": "https://www.newsfocus360.com/2023/10/randeep-hoodas-movie-list.html",
"Rani Mukerji": "https://www.newsfocus360.com/2025/05/rani-mukerji-movies-list.html",
"Ranveer Singh": "https://www.newsfocus360.com/2025/05/ranveer-singh-movies-list.html",
"Rashmika Mandanna": "https://www.newsfocus360.com/2023/10/rashmika-mandanna-movies-list.html",
"Rathika Rose": "https://www.newsfocus360.com/2024/01/rathika-rose-movies-year-wise-complete.html",
"Ravi Mohan": "https://www.newsfocus360.com/2025/05/ravi-mohan-movies-list.html",
"Ravi Teja": "https://www.newsfocus360.com/2023/04/ravi-teja-movies-list.html",
"Rehana": "https://www.newsfocus360.com/2023/12/rehana-movies-year-wise-complete-list.html",
"Rekha": "https://www.newsfocus360.com/2025/05/rekha-movies-list.html",
"Revathy Sampath": "https://www.newsfocus360.com/2025/05/revathy-sampath-movies-list.html",
"Richa Chadha": "https://www.newsfocus360.com/2025/05/richa-chadha-movies-list.html",
"Richard Chamberlain": "https://www.newsfocus360.com/2025/04/richard-chamberlain-movies-list.html",
"Richard Gere": "https://www.newsfocus360.com/2024/01/richard-gere-all-movies-list-year-wise.html",
"Rishi Kapoor": "https://www.newsfocus360.com/2025/05/rishi-kapoor-movies-list.html",
"Riteish Deshmukh": "https://www.newsfocus360.com/2025/04/riteish-deshmukh-movies-list.html",
"Riya Sharma": "https://www.newsfocus360.com/2025/05/riya-sharma-movies-list.html",
"Robert De Niro": "https://www.newsfocus360.com/2024/01/robert-de-niro-all-movies-list-year-wise.html",
"Robert Pattinson": "https://www.newsfocus360.com/2023/10/robert-pattinson-movies-list.html",
"Rooney Mara": "https://www.newsfocus360.com/2024/08/rooney-mara-movies-list-year-wise.html",
"Ryan Coogler": "https://www.newsfocus360.com/2025/05/ryan-coogler-movies-list.html",
"Ryan Reynolds": "https://www.newsfocus360.com/2023/09/ryan-reynolds-movies-list.html",
"S. J. Suryah": "https://www.newsfocus360.com/2023/11/s-j-suryah-all-movies-list.html",
"S. S. Rajamouli": "https://www.newsfocus360.com/2018/12/rajamouli-movies-list.html",
"S. Shankar": "https://www.newsfocus360.com/2024/01/s-shankar-movies-year-wise-complete-list.html",
"Sai Dharam Tej": "https://www.newsfocus360.com/2018/12/Sai-Dharam-Tej-Movies.html",
"Saiee Manjrekar": "https://www.newsfocus360.com/2023/09/saiee-manjrekar-movies-list.html",
"Saif Ali Khan": "https://www.newsfocus360.com/2025/05/saif-ali-khan-movies-list.html",
"Sailesh Kolanu": "https://www.newsfocus360.com/2024/01/sailesh-kolanu-movies-year-wise.html",
"Salman Khan": "https://www.newsfocus360.com/2023/10/salman-khan-movies-list.html",
"Sam Rockwell": "https://www.newsfocus360.com/2025/03/sam-rockwell-movies-list.html",
"Samantha Ruth Prabhu": "https://www.newsfocus360.com/2023/09/samantha-movies-list.html",
"Sana Javed": "https://www.newsfocus360.com/2024/01/sana-javed-movies-list.html",
"Sandeep Pradeep": "https://www.newsfocus360.com/2025/05/sandeep-pradeep-movies-list.html",
"Sandeep Reddy Vanga": "https://www.newsfocus360.com/2023/09/sandeep-reddy-vanga-movies-list.html",
"Sangeeth Sobhan": "https://www.newsfocus360.com/2025/03/sangeeth-sobhan-movies-list.html",
"Sanjay Dutt": "https://www.newsfocus360.com/2025/04/sanjay-dutt-movies-list.html",
"Sanjay Leela Bhansali": "https://www.newsfocus360.com/2025/05/sanjay-leela-bhansali-movies-list.html",
"Sanjay Mishra": "https://www.newsfocus360.com/2024/01/sanjay-mishra-movies-list.html",
"Sanjay Niranjan": "https://www.newsfocus360.com/2025/05/sanjay-niranjan-movies-list.html",
"Sanjeev Kumar": "https://www.newsfocus360.com/2025/05/sanjeev-kumar-movies-list.html",
"Santhanam": "https://www.newsfocus360.com/2024/01/santhanam-movies-list.html",
"Sara Ali Khan": "https://www.newsfocus360.com/2025/05/sara-ali-khan-movies-list.html",
"Sarah Catherine Hook": "https://www.newsfocus360.com/2025/04/sarah-catherine-hook-movies-list.html",
"Sargun Mehta": "https://www.newsfocus360.com/2025/05/sargun-mehta-movies-list.html",
"Satyadev Kancharana": "https://www.newsfocus360.com/2025/05/satyadev-kancharana-movies-list.html",
"Savitri": "https://www.newsfocus360.com/2025/05/savitri-movies-list.html",
"Scarlett Johansson": "https://www.newsfocus360.com/2023/09/scarlett-johansson-movies-list.html",
"Scott Glenn": "https://www.newsfocus360.com/2025/04/scott-glenn-movies-list.html",
"Sekhar Kammula": "https://www.newsfocus360.com/2024/01/sekhar-kammula-movies-list.html",
"Selma Blair": "https://www.newsfocus360.com/2023/10/selma-blair-movies-list.html",
"Shabana Azmi": "https://www.newsfocus360.com/2025/05/shabana-azmi-movies-list.html",
"Shah Rukh Khan": "https://www.newsfocus360.com/2023/11/shahrukh-khan-all-movies-list.html",
"Shahid Kapoor": "https://www.newsfocus360.com/2024/07/shahid-kapoor-all-movies-list-year-wise.html",
"Shammi Kapoor": "https://www.newsfocus360.com/2025/05/shammi-kapoor-movies-list.html",
"Sharaf U Dheen": "https://www.newsfocus360.com/2025/05/sharaf-u-dheen.html",
"Sharmila Tagore": "https://www.newsfocus360.com/2025/05/sharmila-tagore-movies-list.html",
"Sharon Stone": "https://www.newsfocus360.com/2023/10/sharon-stone-movies-list.html",
"Sharwanand": "https://www.newsfocus360.com/2023/12/sharwanand-movies-year-wise-complete.html",
"Shashank": "https://www.newsfocus360.com/2025/05/shashank-movies-list.html",
"Shelley Duvall": "https://www.newsfocus360.com/2024/07/shelley-duvall-all-movies-list-year-wise.html",
"Shhyamali De": "https://www.newsfocus360.com/2025/05/shhyamali-de-movies-list.html",
"Shiny Doshi": "https://www.newsfocus360.com/2025/05/shiny-doshi-movies-list.html",
"Shouryuv": "https://www.newsfocus360.com/2023/11/shouryuv-all-movies-list_25.html",
"Shriya Saran": "https://www.newsfocus360.com/2024/01/shriya-saran-all-movies-list-year-wise.html",
"Shweta Tiwari": "https://www.newsfocus360.com/2025/05/shweta-tiwari-movies-list.html",
"Siddharth": "https://www.newsfocus360.com/2023/10/siddharth-movies-list.html",
"Sidhaant Sachdev": "https://www.newsfocus360.com/2025/04/sidhaant-sachdev-movies-list.html",
"Sidharth Malhotra": "https://www.newsfocus360.com/2023/10/sidharth-malhotra-movies-list.html",
"Silambarasan": "https://www.newsfocus360.com/2024/07/silambarasan-all-movies-list-year-wise.html",
"Simi Garewal": "https://www.newsfocus360.com/2025/05/simi-garewal-movies-list.html",
"Simran": "https://www.newsfocus360.com/2025/04/simran-movies-list.html",
"Sivaji Ganesan": "https://www.newsfocus360.com/2025/05/sivaji-ganesan-movies-list.html",
"Sivakarthikeyan": "https://www.newsfocus360.com/2023/09/sivakarthikeyan-movies-list.html",
"Smeep Kang": "https://www.newsfocus360.com/2025/05/smeep-kang-movies-list.html",
"Smita Patil": "https://www.newsfocus360.com/2025/05/smita-patil-movies-list.html",
"Sobhita Dhulipala": "https://www.newsfocus360.com/2024/12/sobhita-dhulipala-movies-list.html",
"Sofia Carson": "https://www.newsfocus360.com/2025/04/sofia-carson-movies-list.html",
"Sohail Khan": "https://www.newsfocus360.com/2025/04/sohail-khan-movies-list.html",
"Sonu Sood": "https://www.newsfocus360.com/2025/05/sonu-sood-movies-list.html",
"Sooraj Pancholi": "https://www.newsfocus360.com/2025/05/sooraj-pancholi-movies-list.html",
"Sophie Nyweide": "https://www.newsfocus360.com/2025/05/sophie-nyweide-movies-list.html",
"Sophie Thatcher": "https://www.newsfocus360.com/2025/05/sophie-thatcher-movies-list.html",
"Soundarya": "https://www.newsfocus360.com/2024/03/soundarya-movies-list.html",
"Sowmya Menon": "https://www.newsfocus360.com/2024/09/sowmya-menon-movies-list-year-wise.html",
"Spike Lee": "https://www.newsfocus360.com/2024/12/spike-lee-movies-list.html",
"Sree Vishnu": "https://www.newsfocus360.com/2023/12/sree-vishnu-movies-year-wise-complete.html",
"Sreeleela": "https://www.newsfocus360.com/2023/09/sreeleela-movies-list.html",
"Sri Reddy": "https://www.newsfocus360.com/2018/12/sri-reddy-movies-list.html",
"Sridevi": "https://www.newsfocus360.com/2024/07/sridevi-all-movies-list-year-wise.html",
"Srikanth": "https://www.newsfocus360.com/2023/12/srikanth-movies-year-wise-complete-list.html",
"Srikanth Addala": "https://www.newsfocus360.com/2023/09/srikanth-addala-movies-list.html",
"Srinidhi Shetty": "https://www.newsfocus360.com/2025/04/srinidhi-shetty-movies-list.html",
"Srinu Vaitla": "https://www.newsfocus360.com/2023/12/srinu-vaitla-movies-year-wise-complete.html",
"Stephen Graham": "https://www.newsfocus360.com/2025/03/stephen-graham-movies-and-tv-shows-list.html",
"Studio Ghibli": "https://www.newsfocus360.com/2023/09/studio-ghibli-movies-list.html",
"Sudhanshu Pandey": "https://www.newsfocus360.com/2025/05/sudhanshu-pandey-movies-list.html",
"Sudheer Babu": "https://www.newsfocus360.com/2024/06/sudheer-babu-all-movies-list-year-wise.html",
"Suhana Khan": "https://www.newsfocus360.com/2025/05/suhana-khan-movies-list.html",
"Sukumar": "https://www.newsfocus360.com/2018/12/sukumar-movies-list.html",
"Suniel Shetty": "https://www.newsfocus360.com/2025/05/suniel-shetty-movies-list.html",
"Sunita Ahuja": "https://www.newsfocus360.com/2025/05/sunita-ahuja-movies-list.html",
"Sunny Deol": "https://www.newsfocus360.com/2025/05/sunny-deol-movies-list.html",
"Suraj Venjaramoodu": "https://www.newsfocus360.com/2025/05/suraj-venjaramoodu-movies-list.html",
"Surender Reddy": "https://www.newsfocus360.com/2018/12/surender-reddy-movies-list-film-director.html",
"Suriya": "https://www.newsfocus360.com/2023/10/suriya-movies-list.html",
"Sushant Singh Rajput": "https://www.newsfocus360.com/2023/09/sushant-singh-rajput-movies-list.html",
"Sylvester Stallone": "https://www.newsfocus360.com/2024/01/sylvester-stallone-all-movies-list-year.html",
"T. J. Gnanavel": "https://www.newsfocus360.com/2023/10/tj-gnanavel-movies-list.html",
"Taapsee Pannu": "https://www.newsfocus360.com/2024/02/taapsee-pannu-all-movies-list-year-wise.html",
"Tabu": "https://www.newsfocus360.com/2024/04/tabu-movies.html",
"Tamannaah Bhatia": "https://www.newsfocus360.com/2024/01/tamanna-bhatia-all-movies-list-year-wise.html",
"Tapasee Pannu": "https://www.newsfocus360.com/2024/01/tapasee-pannu-all-movies-list-year-wise.html",
"Tara Reid": "https://www.newsfocus360.com/2023/09/tara-reid-movies-list.html",
"Tarun": "https://www.newsfocus360.com/2024/01/tarun-all-movies-list-year-wise.html",
"Tarun Mansukhan": "https://www.newsfocus360.com/2025/05/tarun-mansukhani-movies-list.html",
"Teja Sajja": "https://www.newsfocus360.com/2024/01/teja-sajja-movies-year-wise-complete.html",
"Tharun Bhascker": "https://www.newsfocus360.com/2023/10/tharun-bhascker-movies-list.html",
"Tharun Sudhir": "https://www.newsfocus360.com/2023/12/tharun-sudhir-movies-year-wise-complete.html",
"Tim Burton": "https://www.newsfocus360.com/2023/09/tim-burton-movies-list.html",
"Tim Robbins": "https://www.newsfocus360.com/2025/05/tim-robbins-movies-list.html",
"Timothée Chalamet": "https://www.newsfocus360.com/2023/10/timothee-chalamet-movies-list.html",
"Tom Cruise": "https://www.newsfocus360.com/2023/10/tom-cruise-movies-list.html",
"Tom Hanks": "https://www.newsfocus360.com/2023/04/tom-hanks-movies-list-news-focus-360.html",
"Tom Hardy": "https://www.newsfocus360.com/2025/05/tom-hardy-movies-list.html",
"Tom Holland": "https://www.newsfocus360.com/2023/10/tom-holland-movies-list.html",
"Tony Jaa": "https://www.newsfocus360.com/2023/10/tony-jaa-movies-list.html",
"Tovino Thomas": "https://www.newsfocus360.com/2023/06/tovino-thomas-all-movies-list.html",
"Triptii Dimri": "https://www.newsfocus360.com/2024/12/triptii-dimri-movies-list.html",
"Trisha Krishnan": "https://www.newsfocus360.com/2024/07/trisha-krishnan-all-movies-list-year.html",
"Trivikram Srinivas": "https://www.newsfocus360.com/2023/12/trivikram-srinivas-movies-year-wise.html",
"Udhayanidhi Stalin": "https://www.newsfocus360.com/2023/10/udhayanidhi-stalin-movies-list.html",
"Uma Thurman": "https://www.newsfocus360.com/2023/10/uma-thurman-movies-list.html",
"Urvashi Rautela": "https://www.newsfocus360.com/2025/05/urvashi-rautela-movies-list.html",
"Uttam Kumar": "https://www.newsfocus360.com/2025/05/uttam-kumar-movies-list.html",
"Vaishnavi Chaitanya": "https://www.newsfocus360.com/2024/06/vaishnavi-chaitanya-all-movies-list.html",
"Val Kilmer": "https://www.newsfocus360.com/2025/04/val-kilmer-movies-list.html",
"Varun Dhawan": "https://www.newsfocus360.com/2024/12/varun-dhawan-movies-list.html",
"Vasishta N. Simha": "https://www.newsfocus360.com/2025/04/vasishta-n-simha-movies-list.html",
"Venkat Prabhu": "https://www.newsfocus360.com/2023/10/venkat-prabhu-movies-list.html",
"Venkatesh": "https://www.newsfocus360.com/2018/12/venkatesh-movies-list.html",
"Vennela Kishore": "https://www.newsfocus360.com/2025/05/vennela-kishore-movies-list.html",
"Vetrimaaran": "https://www.newsfocus360.com/2023/10/vetrimaaran-movies-list.html",
"Vichithra": "https://www.newsfocus360.com/2023/11/vichithra-all-movies-list.html",
"Vicky Kaushal": "https://www.newsfocus360.com/2023/10/vicky-kaushal-movies-list.html",
"Vidhu Vinod Chopra": "https://www.newsfocus360.com/2023/12/vidhu-vinod-chopra-movies-year-wise.html",
"Vidya Balan": "https://www.newsfocus360.com/2024/04/vidya-balan-movies-list.html",
"Vidyut Jammwal": "https://www.newsfocus360.com/2023/10/vidyut-jammwal-movies-list.html",
"Vijay": "https://www.newsfocus360.com/2023/09/vijay-movies-list.html",
"Vijay Antony": "https://www.newsfocus360.com/2023/06/vijay-antony-all-movies-list.html",
"Vijay Deverakonda": "https://www.newsfocus360.com/2018/12/vijay-deverakonda-movies-list.html",
"Vijay Kanakamedala": "https://www.newsfocus360.com/2025/05/vijay-kanakamedala-movies-list.html",
"Vijay Karthikeyan": "https://www.newsfocus360.com/2024/12/vijay-karthikeyan-movies-list.html",
"Vijay Sethupathi": "https://www.newsfocus360.com/2024/01/vijay-sethupathi-all-movies-list-year.html",
"Vijaya Shanthi": "https://www.newsfocus360.com/2025/04/vijaya-shanthi-movies-list.html",
"Vijayakanth": "https://www.newsfocus360.com/2018/12/vijayakanth-movies-list.html",
"Vikram": "https://www.newsfocus360.com/2025/03/vikram-movies-list.html",
"Vikram Prabhu": "https://www.newsfocus360.com/2023/10/vikram-prabhu-movies-list.html",
"Vikrant Massey": "https://www.newsfocus360.com/2024/01/vikrant-massey-all-movies-list-year-wise.html",
"vin diesel": "https://www.newsfocus360.com/2025/01/vin-diesel-movies-list.html",
"Vishwak Sen": "https://www.newsfocus360.com/2023/04/vishwak-sen-movies-list.html",
"Vivek Agnihotri": "https://www.newsfocus360.com/2025/05/vivek-agnihotri-movies-list.html",
"Vivica A. Fox": "https://www.newsfocus360.com/2023/09/vivica-fox-movies-list.html",
"Vyjayanthimala": "https://www.newsfocus360.com/2025/05/vyjayanthimala-movies-list.html",
"Waheeda Rehman": "https://www.newsfocus360.com/2025/05/waheeda-rehman-movies-list.html",
"Walton Goggins": "https://www.newsfocus360.com/2025/04/walton-goggins-movies-list.html",
"Wamiqa Gabbi": "https://www.newsfocus360.com/2025/01/wamiqa-gabbi-movies-list.html",
"Wesley Snipes": "https://www.newsfocus360.com/2024/01/wesley-snipes-all-movies-list-year-wise.html",
"Will Smith": "https://www.newsfocus360.com/2023/05/will-smith-movies-list.html",
"Willa Fitzgerald": "https://www.newsfocus360.com/2025/04/willa-fitzgerald-movies-list.html",
"William Holden": "https://www.newsfocus360.com/2024/01/william-holden-all-movies-list-year-wise.html",
"Woodyen Allen": "https://www.newsfocus360.com/2024/01/woody-allen-all-movies-list-year-wise.html",
"Yash": "https://www.newsfocus360.com/2024/12/yash-movies-list.html",
"Yogi Babu": "https://www.newsfocus360.com/2025/04/yogi-babu-movies-list.html",
"Yuva Rajkumar": "https://www.newsfocus360.com/2024/03/yuva-rajkumar-movies-list.html",
"Zarina Wahab": "https://www.newsfocus360.com/2025/05/zarina-wahab-movies-list.html",
"Zeenat Aman": "https://www.newsfocus360.com/2024/01/zeenat-aman-movies-list.html",
"Zendaya": "https://www.newsfocus360.com/2023/10/zendaya-movies-list.html",
"Zoe Saldana": "https://www.newsfocus360.com/2023/09/zoe-saldana-movies-list.html"
    };

    const sortedNames = Object.keys(nameLinks).sort((a, b) => b.length - a.length);
    const nameRegexes = sortedNames.map(name => ({
        name,
        regex: new RegExp(`\\b(${name.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&')})\\b`, 'g')
    }));

    function processNode(node) {
        if (node.nodeType === Node.TEXT_NODE) {
            const parent = node.parentNode;
            if (parent && parent.closest('a')) return; // skip if inside link

            let text = node.nodeValue;
            let hasMatch = false;
            const frag = document.createDocumentFragment();

            while (text.length > 0) {
                let found = false;
                for (let { name, regex } of nameRegexes) {
                    const match = regex.exec(text);
                    if (match) {
                        hasMatch = true;

                        if (match.index > 0) {
                            frag.appendChild(document.createTextNode(text.slice(0, match.index)));
                        }

                        const anchor = document.createElement('a');
                        anchor.href = nameLinks[name];
                        anchor.textContent = `👤 ${match[0]}`;
                        frag.appendChild(anchor);

                        text = text.slice(match.index + match[0].length);
                        found = true;
                        break;
                    }
                }
                if (!found) {
                    frag.appendChild(document.createTextNode(text));
                    break;
                }
            }

            if (hasMatch) {
                parent.replaceChild(frag, node);
            }
        } else if (node.nodeType === Node.ELEMENT_NODE && node.tagName !== 'A') {
            Array.from(node.childNodes).forEach(processNode);
        }
    }

    const targets = document.querySelectorAll('.box-office-cast, .box-office-crew');

    targets.forEach(el => {
        processNode(el);
    });
});
